{"remainingRequest":"/usr/local/var/www/blog/blog/node_modules/babel-loader/lib/index.js!/usr/local/var/www/blog/blog/node_modules/eslint-loader/index.js??ref--13-0!/usr/local/var/www/blog/blog/src/utils/request.js","dependencies":[{"path":"/usr/local/var/www/blog/blog/src/utils/request.js","mtime":1542717380000},{"path":"/usr/local/var/www/blog/blog/node_modules/cache-loader/dist/cjs.js","mtime":499162500000},{"path":"/usr/local/var/www/blog/blog/node_modules/babel-loader/lib/index.js","mtime":499162500000},{"path":"/usr/local/var/www/blog/blog/node_modules/eslint-loader/index.js","mtime":499162500000}],"contextDependencies":[],"result":["import axios from 'axios';\nimport { Message } from 'element-ui';\nimport store from '@/store';\nimport { getToken } from '@/utils/auth'; // create an axios instance\n\nvar service = axios.create({\n  baseURL: process.env.BASE_API,\n  // api 的 base_url\n  timeout: 5000 // request timeout\n\n}); // request interceptor\n\nservice.interceptors.request.use(function (config) {\n  // Do something before request is sent\n  if (store.getters.token) {\n    // 让每个请求携带token-- ['X-Token']为自定义key 请根据实际情况自行修改\n    config.headers['X-Token'] = getToken();\n  }\n\n  return config;\n}, function (error) {\n  // Do something with request error\n  console.log(error); // for debug\n\n  Promise.reject(error);\n}); // response interceptor\n\nservice.interceptors.response.use(function (response) {\n  return response;\n},\n/**\n * 下面的注释为通过在response里，自定义code来标示请求状态\n * 当code返回如下情况则说明权限有问题，登出并返回到登录页\n * 如想通过 xmlhttprequest 来状态码标识 逻辑可写在下面error中\n * 以下代码均为样例，请结合自生需求加以修改，若不需要，则可删除\n */\n// response => {\n//   const res = response.data\n//   if (res.code !== 20000) {\n//     Message({\n//       message: res.message,\n//       type: 'error',\n//       duration: 5 * 1000\n//     })\n//     // 50008:非法的token; 50012:其他客户端登录了;  50014:Token 过期了;\n//     if (res.code === 50008 || res.code === 50012 || res.code === 50014) {\n//       // 请自行在引入 MessageBox\n//       // import { Message, MessageBox } from 'element-ui'\n//       MessageBox.confirm('你已被登出，可以取消继续留在该页面，或者重新登录', '确定登出', {\n//         confirmButtonText: '重新登录',\n//         cancelButtonText: '取消',\n//         type: 'warning'\n//       }).then(() => {\n//         store.dispatch('FedLogOut').then(() => {\n//           location.reload() // 为了重新实例化vue-router对象 避免bug\n//         })\n//       })\n//     }\n//     return Promise.reject('error')\n//   } else {\n//     return response.data\n//   }\n// },\nfunction (error) {\n  console.log('err' + error); // for debug\n\n  Message({\n    message: error.message,\n    type: 'error',\n    duration: 5 * 1000\n  });\n  return Promise.reject(error);\n});\nexport default service;",{"version":3,"sources":["/usr/local/var/www/blog/blog/src/utils/request.js"],"names":["axios","Message","store","getToken","service","create","baseURL","process","env","BASE_API","timeout","interceptors","request","use","config","getters","token","headers","error","console","log","Promise","reject","response","message","type","duration"],"mappings":"AAAA,OAAOA,KAAP,MAAkB,OAAlB;AACA,SAASC,OAAT,QAAwB,YAAxB;AACA,OAAOC,KAAP,MAAkB,SAAlB;AACA,SAASC,QAAT,QAAyB,cAAzB,C,CAEA;;AACA,IAAMC,OAAO,GAAGJ,KAAK,CAACK,MAAN,CAAa;AAC3BC,EAAAA,OAAO,EAAEC,OAAO,CAACC,GAAR,CAAYC,QADM;AACI;AAC/BC,EAAAA,OAAO,EAAE,IAFkB,CAEb;;AAFa,CAAb,CAAhB,C,CAKA;;AACAN,OAAO,CAACO,YAAR,CAAqBC,OAArB,CAA6BC,GAA7B,CACE,UAAAC,MAAM,EAAI;AACR;AACA,MAAIZ,KAAK,CAACa,OAAN,CAAcC,KAAlB,EAAyB;AACvB;AACAF,IAAAA,MAAM,CAACG,OAAP,CAAe,SAAf,IAA4Bd,QAAQ,EAApC;AACD;;AACD,SAAOW,MAAP;AACD,CARH,EASE,UAAAI,KAAK,EAAI;AACP;AACAC,EAAAA,OAAO,CAACC,GAAR,CAAYF,KAAZ,EAFO,CAEY;;AACnBG,EAAAA,OAAO,CAACC,MAAR,CAAeJ,KAAf;AACD,CAbH,E,CAgBA;;AACAd,OAAO,CAACO,YAAR,CAAqBY,QAArB,CAA8BV,GAA9B,CACE,UAAAU,QAAQ;AAAA,SAAIA,QAAJ;AAAA,CADV;AAEE;;;;;;AAMA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA,UAAAL,KAAK,EAAI;AACPC,EAAAA,OAAO,CAACC,GAAR,CAAY,QAAQF,KAApB,EADO,CACoB;;AAC3BjB,EAAAA,OAAO,CAAC;AACNuB,IAAAA,OAAO,EAAEN,KAAK,CAACM,OADT;AAENC,IAAAA,IAAI,EAAE,OAFA;AAGNC,IAAAA,QAAQ,EAAE,IAAI;AAHR,GAAD,CAAP;AAKA,SAAOL,OAAO,CAACC,MAAR,CAAeJ,KAAf,CAAP;AACD,CA3CH;AA8CA,eAAed,OAAf","sourcesContent":["import axios from 'axios'\nimport { Message } from 'element-ui'\nimport store from '@/store'\nimport { getToken } from '@/utils/auth'\n\n// create an axios instance\nconst service = axios.create({\n  baseURL: process.env.BASE_API, // api 的 base_url\n  timeout: 5000 // request timeout\n})\n\n// request interceptor\nservice.interceptors.request.use(\n  config => {\n    // Do something before request is sent\n    if (store.getters.token) {\n      // 让每个请求携带token-- ['X-Token']为自定义key 请根据实际情况自行修改\n      config.headers['X-Token'] = getToken()\n    }\n    return config\n  },\n  error => {\n    // Do something with request error\n    console.log(error) // for debug\n    Promise.reject(error)\n  }\n)\n\n// response interceptor\nservice.interceptors.response.use(\n  response => response,\n  /**\n   * 下面的注释为通过在response里，自定义code来标示请求状态\n   * 当code返回如下情况则说明权限有问题，登出并返回到登录页\n   * 如想通过 xmlhttprequest 来状态码标识 逻辑可写在下面error中\n   * 以下代码均为样例，请结合自生需求加以修改，若不需要，则可删除\n   */\n  // response => {\n  //   const res = response.data\n  //   if (res.code !== 20000) {\n  //     Message({\n  //       message: res.message,\n  //       type: 'error',\n  //       duration: 5 * 1000\n  //     })\n  //     // 50008:非法的token; 50012:其他客户端登录了;  50014:Token 过期了;\n  //     if (res.code === 50008 || res.code === 50012 || res.code === 50014) {\n  //       // 请自行在引入 MessageBox\n  //       // import { Message, MessageBox } from 'element-ui'\n  //       MessageBox.confirm('你已被登出，可以取消继续留在该页面，或者重新登录', '确定登出', {\n  //         confirmButtonText: '重新登录',\n  //         cancelButtonText: '取消',\n  //         type: 'warning'\n  //       }).then(() => {\n  //         store.dispatch('FedLogOut').then(() => {\n  //           location.reload() // 为了重新实例化vue-router对象 避免bug\n  //         })\n  //       })\n  //     }\n  //     return Promise.reject('error')\n  //   } else {\n  //     return response.data\n  //   }\n  // },\n  error => {\n    console.log('err' + error) // for debug\n    Message({\n      message: error.message,\n      type: 'error',\n      duration: 5 * 1000\n    })\n    return Promise.reject(error)\n  }\n)\n\nexport default service\n"]}]}